# Site settings
title: metadua.com
email: metadua@metadua.com
description: > # this means to ignore newlines until "baseurl:"
  We intend to be providing the absolute best in data-management solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.metadua.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  metadua

# Build settings
markdown: kramdown
