# Site settings
title: metadua
email: metadua@metadua.com
description: > # this means to ignore newlines until "baseurl:"
  metadua.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.metadua.com" # the base hostname & protocol for your site

# User setting
owner: metadua.com
email: metadua@metadua.com
facebook_username:
twitter_username:
github_username: metadua
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: metadua.com

# API settings
google_api_key:

# Build settings
markdown: kramdown